### Get Boards
GET http://localhost:8080/api/v1/boards

### Create a new board
POST http://localhost:8080/api/v1/boards
Content-Type: application/json

{
    "username": "shells",
    "boardName": "test_board",
    "images": [
    ],
    "thumbnail": "",
    "customThumbnail": false
}

### Get a specific user's boards
GET http://localhost:8080/api/v1/boards/leon

### Get a specific board from a user
//TELL FRONTEND SEND URLS WITH SPACES REPLACED WITH DASHES
GET http://localhost:8080/api/v1/boards/leon/cool images

### Delete a specific board from a user
DELETE http://localhost:8080/api/v1/boards/leon
Content-Type: application/json

{
    "boardName": "dog12"
}

### Adding and deleting an image into a specific board
PATCH http://localhost:8080/api/v1/boards/leon
Content-Type: application/json

{
    "boardName": "cool images",
    "images": [],
    "imageUpdates": [
      {
      "url": "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2022-08/220805-border-collie-play-mn-1100-82d2f1.jpg",
      "prompt": "1"
      }
    ],
    "deleteImage": true,
    "isCustomThumbnail": true
}

### Change a board's thumnail and board name
PATCH http://localhost:8080/api/v1/boards/leon/cool images
Content-Type: application/json

 {
    "newThumbnailUrl": "image4",
    "newBoardName": "cool images"
 }
